mode "app-launcher" {
    bindsym b exec firefox, mode "default"
    bindsym Shift+b exec firefox --private-window, mode "default"

    bindsym m exec flatpak run com.spotify.Client, mode "default"

    bindsym f exec alacritty -e lf, mode "default"
    bindsym Shift+f exec thunar, mode "default"

    bindsym Escape mode "default"
}
bindsym $mod+Space mode "app-launcher"
