# Colors
set $bg       #0b0b0b
set $surface  #18191a
set $focused  #00b0ff
set $inactive #282a2d
set $text     #ffffff
set $subtext  #676e7b

# Window Borders & Title Bars
# Class                 Border    BG        Text     Indicator Child_Border
client.focused           $focused  $surface  $text    $focused  $focused
client.focused_inactive  $inactive $surface  $subtext $inactive $inactive
client.unfocused         $inactive $surface  $subtext $inactive $inactive
client.urgent            #ff5252   #ff5252   $text    #ff5252   #ff5252

# Default Border Widths
default_border pixel 2
default_floating_border pixel 2
for_window [app_id=".*"] border pixel 2
for_window [class=".*"] border pixel 2
