set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -as terminal-overrides ",alacritty:Tc,xterm-256color:Tc"
set -g focus-events on
set -sg escape-time 0
set -g mouse on

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

set -g extended-keys on
set -s extended-keys on
set -as terminal-features ',xterm*:extkeys,alacritty:extkeys,kitty:extkeys'

set -g status-interval 1
set -g status-style "bg=#{?#(cat /sys/class/leds/input*::capslock/brightness 2>/dev/null | grep -q '1' && echo 1 || echo 0),red,#262626},fg=#b2b2b2"

set -g status-left "#[fg=#ffffff,bold] [#S] "
set -g status-left-length 20

set -g window-status-current-style bg=#007acc,fg=#ffffff,bold
set -g window-status-current-format " #I:#W#F "
set -g window-status-style bg=default,fg=#b2b2b2
set -g window-status-format " #I:#W#F "

set -g status-right "#[bg=default,fg=#8a8a8a] %H:%M │ %d-%b-%y "
set -g status-right-length 50

bind-key -n C-1 select-window -t 1
bind-key -n C-2 select-window -t 2
bind-key -n C-3 select-window -t 3
bind-key -n C-4 select-window -t 4
bind-key -n C-5 select-window -t 5

bind-key -n C-PageUp previous-window
bind-key -n C-PageDown next-window
bind-key -n S-Enter send-keys "\\" Enter
bind-key -n C-Home new-window -c "#{pane_current_path}"

setw -g mode-keys vi
is_vim="ps -o state= -o comm= -t '#{client_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?|fzf)(diff)?$'"

bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j' 'select-pane -L'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k' 'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l' 'select-pane -D'
bind-key -n 'C-;' if-shell "$is_vim" 'send-keys C-\;' 'select-pane -R'

bind-key -n M-s copy-mode
bind-key -T copy-mode-vi j send-keys -X cursor-left
bind-key -T copy-mode-vi k send-keys -X cursor-up
bind-key -T copy-mode-vi l send-keys -X cursor-down
bind-key -T copy-mode-vi \; send-keys -X cursor-right

bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y if-shell -F "#{selection_present}" {
    if-shell "[[ -n \$SSH_CLIENT || -n \$SSH_TTY ]]" {
        send-keys -X copy-pipe-and-cancel "base64 | tr -d '\n' | xargs -I {} tmux run-shell 'printf \"\\033]52;c;{}\\007\" > \"#{client_tty}\"'"
    } {
        if-shell "[[ -n \$DISPLAY || -n \$WAYLAND_DISPLAY ]]" {
            send-keys -X copy-pipe-and-cancel "wl-copy"
        } {
            send-keys -X copy-pipe-and-cancel "base64 | tr -d '\n' | xargs -I {} tmux run-shell 'printf \"\\033]52;c;{}\\007\" > \"#{client_tty}\"'"
        }
    }
} {
    send-keys -X select-line
}
bind-key -T copy-mode-vi i send-keys -X cancel

set -g allow-passthrough on
set -s set-clipboard on

set -as terminal-features ',xterm-256color:Clipboard,tmux-256color:Clipboard,alacritty:Clipboard'
set -as terminal-overrides ",xterm-256color:Ms=\\E]52;%p1%s;%p2%s\\7,tmux-256color:Ms=\\E]52;%p1%s;%p2%s\\7,alacritty:Ms=\\E]52;%p1%s;%p2%s\\7"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'JosephLai241/tmux-line-numbers'
set -g @line-numbers-relative on

run '~/.tmux/plugins/tpm/tpm'

set -g pane-border-style fg=#333333
set -g pane-active-border-style fg=#333333

set -s user-keys[0] "\e[9001~"
set -s user-keys[1] "\e[9002~"

bind-key -n User0 select-pane -t '{previous}'
bind-key -n User1 select-pane -t '{next}'
